#!/bin/bash

DIR="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT=$(dirname ${DIR})
FILE="${ROOT}/fib.txt"

previous=1
current=1
if [ -f ${FILE} ]; then
    previous=$(head -n 1 ${FILE})
    current=$(tail -n 1 ${FILE})
fi

# These get large fast so we rely on Python's arbitrarily large integers.
next=$(python -c "print ${previous} + ${current}")
echo "${current}
${next}" > ${FILE}

cd ${ROOT}
git add ${FILE}
git commit -m "Recording a new Fibonacci number: ${next}."
git push
